Double [[]], {} instead of subshell

diff --git a/scripts/docker/ca/Dockerfile b/scripts/docker/ca/Dockerfile
--- a/scripts/docker/ca/Dockerfile
+++ b/scripts/docker/ca/Dockerfile
@@ -14,8 +14,8 @@ COPY ./generate_ca_crt.sh .
 
 ARG CA_ADMIN_HOME
 RUN <<EOF
-if [ -z "${CA_ADMIN_HOME}" ]; then \
-    echo "Error! \"CA_ADMIN_HOME\" argument is not provided!"
+if [[ -z "${CA_ADMIN_HOME}" ]]; then \
+    echo "Error! \"CA_ADMIN_HOME\" argument is not provided!" >&2
     exit 1
 fi
 EOF
